#!/usr/bin/env python3
"""英語タイトル・紹介文を日本語化するスクリプト v2

戦略:
- フレーズ→単語の優先順で長いものから置換 (regex 単語境界)
- 既に日本語の文は触らない
- 元データは index.en.json にバックアップ
- カンマは「、」に変換、末尾に「。」を補う

site/data/index.json を読んで site/data/index.json に上書き保存。
"""
import json, re, shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC  = ROOT / 'site' / 'data' / 'index.json'
BAK  = ROOT / 'site' / 'data' / 'index.en.json'

# ─────────────────────────────────────────────────────
# タイトル翻訳: 完全一致マップ + 単語マップ
# ─────────────────────────────────────────────────────
TITLE_FULL = {
    'Midnight Pour Over': '真夜中のドリップ',
    'Concrete Slams': 'コンクリート・スラム',
    'Breaking Report': '速報',
    'Bouncy Bumble Parade': '弾むパレード',
    'Bouncy Tuba Parade': '陽気なチューバのパレード',
    'Merry Eve Snowfall': '聖夜の雪',
    'Shibuya Dust Loop': '渋谷ダスト・ループ',
    'Summit Signal': '頂上のシグナル',
    'Paper Skies': '紙の空',
    'Open Window Morning': '朝の窓辺',
    'Window Rain Loops': '窓辺の雨',
    'Sakura Festival': '桜祭り',
    'Cookie Parade': 'クッキー・パレード',
    'Boardroom Momentum': '会議室の高揚',
    'Ramen Steam Drift': 'ラーメンの湯気',
}

TITLE_WORDS = {
    # 時間
    'Midnight': '真夜中', 'Morning': '朝', 'Evening': '夕暮れ', 'Afternoon': '午後',
    'Night': '夜', 'Day': '昼', 'Dawn': '夜明け', 'Dusk': '黄昏',
    'Sunrise': '日の出', 'Sunset': '日没', 'Twilight': '黄昏', 'Midday': '正午',
    # 季節・自然
    'Spring': '春', 'Summer': '夏', 'Autumn': '秋', 'Winter': '冬',
    'Snow': '雪', 'Snowfall': '雪', 'Rain': '雨', 'Storm': '嵐',
    'Cloud': '雲', 'Clouds': '雲', 'Sky': '空', 'Skies': '空',
    'Sun': '太陽', 'Moon': '月', 'Star': '星', 'Stars': '星',
    'Wind': '風', 'Breeze': 'そよ風', 'Mist': '霞', 'Fog': '霧',
    'Frost': '霜', 'Ice': '氷', 'Heat': '熱',
    # 場所
    'Window': '窓', 'Door': '扉', 'Garden': '庭', 'Park': '公園',
    'Forest': '森', 'River': '川', 'Sea': '海', 'Ocean': '海',
    'Lake': '湖', 'Mountain': '山', 'Mountains': '山々', 'Hill': '丘',
    'Cafe': 'カフェ', 'City': '街', 'Town': '町', 'Village': '村',
    'Tokyo': '東京', 'Kyoto': '京都', 'Shibuya': '渋谷', 'Osaka': '大阪',
    'Beach': 'ビーチ', 'Shore': '岸辺', 'Sand': '砂',
    'School': '学校', 'Library': '図書館', 'Office': 'オフィス',
    'Boardroom': '会議室', 'Studio': 'スタジオ', 'Mall': 'モール',
    'Bedroom': '寝室', 'Kitchen': 'キッチン', 'Field': '野原',
    'Fields': '野原', 'Meadow': '草原',
    # 音楽用語
    'Loop': 'ループ', 'Loops': 'ループ', 'Beat': 'ビート', 'Beats': 'ビート',
    'Groove': 'グルーヴ', 'Drift': '漂い', 'Float': '浮遊',
    'Bass': 'ベース', 'Synth': 'シンセ', 'Piano': 'ピアノ',
    'Guitar': 'ギター', 'Drum': 'ドラム', 'Drums': 'ドラム',
    'Strings': 'ストリングス', 'Flute': 'フルート', 'Violin': 'バイオリン',
    'Tuba': 'チューバ', 'Trumpet': 'トランペット', 'Sax': 'サックス',
    'Saxophone': 'サックス',
    'Punk': 'パンク', 'Rock': 'ロック', 'Jazz': 'ジャズ', 'Funk': 'ファンク',
    'Soul': 'ソウル', 'Pop': 'ポップ', 'Folk': 'フォーク',
    'Boom': 'ブーム', 'Bap': 'バップ', 'Hop': 'ホップ',
    # 雰囲気
    'Bouncy': '弾む', 'Sweet': '甘い', 'Soft': '優しい', 'Bright': '明るい',
    'Dark': '暗い', 'Warm': '温かい', 'Cool': '涼しい', 'Cold': '冷たい',
    'Quiet': '静かな', 'Loud': '激しい', 'Calm': '穏やかな', 'Wild': '荒々しい',
    'Open': '開いた', 'Lone': '孤独な', 'Alone': '一人',
    'Lost': '迷子の', 'Found': '見つけた', 'Hidden': '隠れた', 'Secret': '秘密の',
    'Final': '最後の', 'First': '最初の', 'Last': '最後の', 'Next': '次の',
    'Slow': 'スロー', 'Fast': '速い', 'Quick': '素早い',
    'Old': '古い', 'New': '新しい', 'Young': '若い',
    'Little': '小さな', 'Big': '大きな', 'Tiny': '小さな', 'Huge': '巨大な',
    # 名詞
    'Heart': '心', 'Soul': '魂', 'Dream': '夢', 'Dreams': '夢',
    'Memory': '記憶', 'Memories': '記憶', 'Story': '物語', 'Tale': '物語',
    'Journey': '旅', 'Path': '道', 'Road': '道', 'Trip': '旅',
    'Festival': '祭り', 'Parade': 'パレード', 'Celebration': '祝祭',
    'Adventure': '冒険', 'Quest': '探求', 'Battle': '戦い', 'Victory': '勝利',
    'Hero': '英雄', 'Magic': '魔法', 'Wonder': '驚き', 'Mystery': '神秘',
    'Smile': '微笑み', 'Laugh': '笑い', 'Tear': '涙', 'Tears': '涙',
    'Hope': '希望', 'Faith': '信念', 'Wish': '願い', 'Peace': '平和',
    # 季節物
    'Sakura': '桜', 'Cherry': '桜', 'Blossom': '花', 'Blossoms': '花',
    'Christmas': 'クリスマス', 'Holiday': '休日', 'Eve': 'イブ',
    # その他
    'Concrete': 'コンクリート', 'Slams': 'スラム', 'Slam': 'スラム',
    'Cookie': 'クッキー', 'Honey': 'ハニー', 'Sugar': 'シュガー',
    'Candy': 'キャンディ', 'Lemon': 'レモン', 'Mint': 'ミント',
    'Coffee': 'コーヒー', 'Espresso': 'エスプレッソ', 'Latte': 'ラテ',
    'Tea': '紅茶', 'Cake': 'ケーキ', 'Ramen': 'ラーメン',
    'Sushi': '寿司', 'Sake': '酒',
    'Paper': '紙', 'Glass': 'ガラス', 'Stone': '石', 'Wood': '木',
    'Metal': '金属', 'Velvet': 'ベルベット', 'Silk': 'シルク',
    'Sound': '音', 'Voice': '声', 'Whisper': 'ささやき', 'Echo': '響き',
    'Step': '一歩', 'Steps': '足音', 'Walk': '歩み', 'Run': '走り',
    'Pour': '注ぐ', 'Over': '越え',
    'Summit': '頂上', 'Signal': 'シグナル',
    'Urban': '都会', 'Bumble': 'バンブル', 'Merry': '陽気な',
    'Steam': '湯気', 'Dust': 'ダスト',
    'Glow': '輝き', 'Shine': '光', 'Shimmer': 'きらめき', 'Sparkle': 'きらめき',
    'Light': '光', 'Shadow': '影', 'Reflection': '反射',
    'Letter': '手紙', 'Postcard': '葉書', 'Picnic': 'ピクニック',
    'Bird': '鳥', 'Birds': '鳥たち', 'Cat': '猫', 'Dog': '犬', 'Fox': '狐',
    'Train': '電車', 'Plane': '飛行機', 'Car': '車', 'Boat': '船',
    'Toy': 'おもちゃ', 'Toys': 'おもちゃ', 'Doll': '人形',
    'Pixel': 'ピクセル', 'Digital': 'デジタル', 'Analog': 'アナログ',
    'Neon': 'ネオン', 'Laser': 'レーザー', 'Cosmic': '宇宙',
    'Crystal': 'クリスタル', 'Gold': '金', 'Silver': '銀',
    'Lullaby': '子守唄', 'Anthem': 'アンセム', 'Theme': 'テーマ',
    'Ballad': 'バラード', 'March': 'マーチ', 'Waltz': 'ワルツ',
    'Mood': 'ムード', 'Vibe': 'ムード', 'Feel': '感覚',
    'Time': '時', 'Hour': '時間',
    'Plum': '梅', 'Bamboo': '竹',
    'Matsuri': '祭り', 'Yukata': '浴衣',
    'Fire': '炎', 'Spark': '火花', 'Sparks': '火花',
    'Stream': '小川', 'Wave': '波', 'Waves': '波',
    'Flower': '花', 'Flowers': '花々', 'Petal': '花びら', 'Petals': '花びら',
    'Feather': '羽', 'Wing': '翼', 'Wings': '翼',
    'Diamond': 'ダイヤ', 'Apple': '林檎', 'Orange': 'オレンジ',
    'Peach': '桃', 'Maple': '紅葉',
    'Leaf': '葉', 'Leaves': '葉', 'Trees': '木々', 'Tree': '木',
    'Green': '緑', 'Blue': '青', 'Red': '赤', 'Yellow': '黄',
    'Pink': 'ピンク', 'Purple': '紫', 'White': '白', 'Black': '黒',
    'Latte': 'ラテ', 'Macchiato': 'マキアート',
    'Diner': 'ダイナー', 'Restaurant': 'レストラン',
    'Avenue': '通り', 'Street': '通り', 'Alley': '路地',
    'Bridge': '橋', 'Tower': '塔', 'Castle': '城', 'Temple': '寺院',
    'Shrine': '神社',
    'Sushi': '寿司', 'Tonkatsu': 'とんかつ',
    'Pop': 'ポップ',
    'Note': '音符', 'Notes': '音符',
    'Pulse': '脈動', 'Tide': '潮',
    'Tide': '潮', 'Shoreline': '岸辺',
}

# ─────────────────────────────────────────────────────
# 紹介文用 大辞書 (長いフレーズから置換)
# ─────────────────────────────────────────────────────
PHRASE_PAIRS = [
    # ── 追加3: 最終仕上げ ──
    ('lazy Sunday', '怠惰な日曜'),
    ('lazy', '怠惰な'),
    ('Sunday', '日曜'),
    ('Saturday', '土曜'),
    ('weekend', '週末'),
    ('weekday', '平日'),
    ('Monday morning', '月曜の朝'),
    ('Monday', '月曜'),
    ('Friday night', '金曜の夜'),
    ('Friday', '金曜'),
    ('8-bit chiptune', '8ビット・チップチューン'),
    ('8-bit', '8ビット'),
    ('chiptune', 'チップチューン'),
    ('NES style', 'NES風'),
    ('NES', 'NES'),
    ('SNES', 'スーファミ風'),
    ('Game Boy', 'ゲームボーイ'),
    ('arcade', 'アーケード'),
    ('retro game', 'レトロゲーム'),
    ('video game', 'ビデオゲーム'),
    ('adventurous exploration theme', '冒険的な探索のテーマ'),
    ('adventurous exploration', '冒険的な探索'),
    ('adventurous', '冒険的な'),
    ('exploration', '探索'),
    ('pixel art', 'ピクセルアート'),
    ('carefree daily Vlog', '気ままな日常Vlog'),
    ('carefree daily', '気ままな日常'),
    ('carefree', '気ままな'),
    ('daily', '日常の'),
    ('neon city', 'ネオン街'),
    ('neon', 'ネオン'),
    ('midnight walk', '深夜の散歩'),
    ('midnight drive', '真夜中のドライブ'),
    ('midnight', '真夜中'),
    ('lazy drums', 'のんびりしたドラム'),
    ('lazy beat', 'のんびりしたビート'),
    ('cozy room', '心地よい部屋'),
    ('room', '部屋'),
    ('city pop influence', 'シティポップの影響'),
    ('city pop vibe', 'シティポップの雰囲気'),
    ('influence', '影響'),
    ('insert song', '挿入歌'),
    ('insertsong', '挿入歌'),
    ('pop idol', 'ポップアイドル'),
    ('idol BGM', 'アイドルBGM'),
    ('idol', 'アイドル'),
    ('indie folk', 'インディーフォーク'),
    ('indie pop', 'インディーポップ'),
    ('indie rock', 'インディーロック'),
    ('indie', 'インディー'),
    ('folk BGM', 'フォークBGM'),
    ('folk pop', 'フォークポップ'),
    ('folk', 'フォーク'),
    ('Blade Runner', 'ブレードランナー'),
    ('cyberpunk', 'サイバーパンク'),
    ('film noir', 'フィルムノワール'),
    ('noir', 'ノワール'),
    ('haunted shrine', '幽霊神社'),
    ('haunted', '幽霊の'),
    ('unsettling silence', '不穏な静寂'),
    ('unsettling', '不穏な'),
    ('silence', '静寂'),
    ('ghost story', '怪談'),
    ('ghost', '幽霊'),
    ('memory', '記憶'),
    ('memories', '思い出'),
    ('inspiring', '感動的な'),
    ('inspiration', 'インスピレーション'),
    ('rpg', 'RPG'),
    ('RPG', 'RPG'),
    ('JRPG', 'JRPG'),
    ('psychological', '心理的'),
    ('psychological horror', '心理的ホラー'),
    ('silky', 'シルキーな'),
    ('silky smooth', 'シルキースムース'),
    ('holiday season', 'ホリデーシーズン'),
    ('holiday', '休日'),
    ('trio', 'トリオ'),
    ('quartet', 'カルテット'),
    ('duet', 'デュエット'),
    ('sensual', '官能的な'),
    ('lifestyle', 'ライフスタイル'),
    ('loop', 'ループ'),
    ('looped', 'ループした'),
    ('hauntedshrine', '幽霊神社'),
    ('newbeginningtheme', '新たな始まりのテーマ'),
    ('sunrisefeeling', '日の出の感覚'),
    ('Itali', 'イタリアン'),

    # ── 追加2: 残り未訳ワード ──
    ('new beginning theme', '新たな始まりのテーマ'),
    ('new beginning', '新たな始まり'),
    ('sunrise feeling', '日の出の感覚'),
    ('sunrise', '日の出'),
    ('pure and simple', '純粋でシンプル'),
    ('pure', '純粋な'),
    ('simple', 'シンプル'),
    ('nature ambient', '自然アンビエント'),
    ('Nature ambient', '自然アンビエント'),
    ('nature', '自然'),
    ('sounds of', 'の音'),
    ('sounds', '音'),
    ('river stream', '小川のせせらぎ'),
    ('riverstream', '小川'),
    ('river', '川'),
    ('stream', 'せせらぎ'),
    ('documentary BGM', 'ドキュメンタリーBGM'),
    ('documentary', 'ドキュメンタリー'),
    ('Italian cafe', 'イタリアンカフェ'),
    ('Italian', 'イタリアン'),
    ('italian', 'イタリアン'),
    ('Brazilian', 'ブラジル'),
    ('brazilian', 'ブラジル'),
    ('bossa nova', 'ボサノバ'),
    ('bossanova', 'ボサノバ'),
    ('Mexican', 'メキシカン'),
    ('Spanish', 'スパニッシュ'),
    ('French', 'フレンチ'),
    ('Hawaiian', 'ハワイアン'),
    ('Cuban', 'キューバン'),
    ('African', 'アフリカン'),
    ('Indian', 'インド'),
    ('Chinese', '中国'),
    ('Korean', '韓国'),
    ('Russian', 'ロシア'),
    ('Celtic', 'ケルト'),
    ('Latin', 'ラテン'),
    ('808 bass', '808ベース'),
    ('hi-hat rolls', 'ハイハットロール'),
    ('hi-hat', 'ハイハット'),
    ('hihat', 'ハイハット'),
    ('rolls', 'ロール'),
    ('street energy', 'ストリート感'),
    ('street', 'ストリート'),
    ('gaming highlights montage', 'ゲームハイライト映像'),
    ('gaming highlights', 'ゲームハイライト'),
    ('gaming montage', 'ゲーム映像'),
    ('gaming', 'ゲーム'),
    ('highlights', 'ハイライト'),
    ('highlight', 'ハイライト'),
    ('montages', '映像集'),
    ('montage', '映像'),
    ('meets', '〜と出会う'),
    ('zen', '禅'),
    ('zen garden', '禅の庭'),
    ('pads', 'パッド'),
    ('pad', 'パッド'),
    ('full orchestra', 'フルオーケストラ'),
    ('orchestra', 'オーケストラ'),
    ('rising', '高まる'),
    ('rising synth', '高まるシンセ'),
    ('ending theme', 'エンディングテーマ'),
    ('ending', 'エンディング'),
    ('opening', 'オープニング'),
    ('intro', 'イントロ'),
    ('outro', 'アウトロ'),
    ('kawaii', 'かわいい'),
    ('shuffled drums', 'シャッフルしたドラム'),
    ('shuffled', 'シャッフルした'),
    ('shuffle', 'シャッフル'),
    ('creepy', '不気味な'),
    ('chilling', 'ゾッとする'),
    ('suspenseful', 'サスペンス感のある'),
    ('suspense', 'サスペンス'),
    ('funny', 'ユーモラス'),
    ('humorous', 'ユーモラス'),
    ('comical', 'コミカル'),
    ('arpeggios', 'アルペジオ'),
    ('arpeggio', 'アルペジオ'),
    ('fingerpicking', 'フィンガーピッキング'),
    ('fingerpicked', 'フィンガーピッキング'),
    ('sweet', '甘い'),
    ('dance', 'ダンス'),
    ('dance music', 'ダンスミュージック'),
    ('dancehall', 'ダンスホール'),
    ('Mozart', 'モーツァルト'),
    ('Chopin', 'ショパン'),
    ('Bach', 'バッハ'),
    ('Beethoven', 'ベートーベン'),
    ('Baroque', 'バロック'),
    ('jazzy Rhodes', 'ジャジーなローズ'),
    ('mellow Rhodes', 'メロウなローズ'),
    ('analog warmth', 'アナログの温かさ'),
    ('analog', 'アナログ'),
    ('tape', 'テープ'),
    ('tape hiss', 'テープノイズ'),
    ('reverb', 'リバーブ'),
    ('delay', 'ディレイ'),
    ('echo', 'エコー'),
    ('lush', '豊かな'),
    ('warm pads', '温かいパッド'),
    ('soft pads', '柔らかなパッド'),
    ('big', '大きな'),
    ('huge', '巨大な'),
    ('tiny', '小さな'),
    ('layered', '層を成す'),
    ('processed', '加工された'),
    ('clean', 'クリーン'),
    ('lo-fi production', 'Lo-Fi制作'),
    ('production', '制作'),

    # ── 追加: よく出る複合フレーズ ──
    ('celebration of new beginning', '新たな始まりを祝う'),
    ('celebration of', '〜の祝祭'),
    ('celebration', '祝祭'),
    ('walking bass', 'ウォーキングベース'),
    ('walking', '散歩'),
    ('birds chirping', '鳥のさえずり'),
    ('birds and nature sounds', '鳥と自然の音'),
    ('nature sounds', '自然の音'),
    ('vinyl crackle', 'レコードのノイズ'),
    ('vinyl', 'ヴァイナル'),
    ('crackle', 'ぱちぱち音'),
    ('sparkly piano', 'きらめくピアノ'),
    ('sparkly synth', 'きらめくシンセ'),
    ('sparkly', 'きらめく'),
    ('breezy guitar licks', '爽やかなギターリック'),
    ('breezy guitar', '爽やかなギター'),
    ('breezy', '爽やかな'),
    ('upright bass', 'ウッドベース'),
    ('upright piano', 'アップライトピアノ'),
    ('upright', 'アップライト'),
    ('brushed drums', 'ブラシドラム'),
    ('brushed snare', 'ブラシスネア'),
    ('brushed', 'ブラシ'),
    ('meditation music', '瞑想音楽'),
    ('meditation', '瞑想'),
    ('meditative', '瞑想的な'),
    ('electric piano', 'エレピ'),
    ('electric guitar', 'エレキギター'),
    ('electric bass', 'エレキベース'),
    ('electric', 'エレクトリック'),
    ('free BGM', 'フリーBGM'),
    ('free background music', 'フリーBGM'),
    ('intro music', 'イントロ音楽'),
    ('intros', 'イントロ'),
    ('intro', 'イントロ'),
    ('outro', 'アウトロ'),
    ('solo piano', 'ピアノソロ'),
    ('solo guitar', 'ギターソロ'),
    ('solo', 'ソロ'),
    ('light and joyful', '軽やかで楽しい'),
    ('light percussion', '軽やかなパーカッション'),
    ('light beat', '軽やかなビート'),
    ('light pop', '軽やかなポップ'),
    ('light music', '軽やかな音楽'),
    ('light', '軽やかな'),
    ('heavy bass', '重低音'),
    ('heavy drums', '重いドラム'),
    ('heavy', '重い'),
    ('youthful energy', '若々しいエネルギー'),
    ('youthful', '若々しい'),
    ('appetizing', '食欲をそそる'),
    ('energy', 'エネルギー'),
    ('bells', 'ベル'),
    ('traditional Japanese', '日本の伝統的な'),
    ('traditional instruments', '伝統楽器'),
    ('traditional', '伝統的な'),
    ('inviting', '心地よい'),
    ('slow tempo', 'スローテンポ'),
    ('mid tempo', 'ミドルテンポ'),
    ('fast tempo', 'ファストテンポ'),
    ('sunny day', '晴れた日'),
    ('sunny', '晴れた'),
    ('dim lights', '薄暗い照明'),
    ('intimate and sophisticated', '親密で洗練された'),
    ('intimate', '親密な'),
    ('jazz bar', 'ジャズバー'),
    ('cocktail bar', 'カクテルバー'),
    ('lounge bar', 'ラウンジバー'),
    ('rhythm section', 'リズム隊'),
    ('sunset drive', '夕日ドライブ'),
    ('sunset', '夕日'),
    ('80s nostalgia', '80年代ノスタルジア'),
    ('80s', '80年代'),
    ('70s', '70年代'),
    ('90s', '90年代'),
    ('catchy melody', 'キャッチーなメロディ'),
    ('cheerful and youthful', '陽気で若々しい'),
    ('Japanese gardening', '日本の庭づくり'),
    ('plant care', '植物の手入れ'),
    ('peaceful and nurturing', '穏やかで包み込むような'),
    ('nurturing', '包み込むような'),
    ('gentle acoustic guitar', '優しいアコースティックギター'),
    ('mellow trumpet', 'メロウなトランペット'),
    ('drive', 'ドライブ'),
    ('groove', 'グルーヴ'),

    # ── 長フレーズ (BGM ラベル) ──
    ('Neo soul BGM', 'ネオソウルBGM'),
    ('Punk rock BGM', 'パンクロックBGM'),
    ('News broadcast BGM', 'ニュース番組風BGM'),
    ('Fun children BGM', '楽しい子ども向けBGM'),
    ('Happy cartoon BGM', '陽気なカートゥーンBGM'),
    ('Summer festival BGM', '夏祭りBGM'),
    ('Christmas BGM', 'クリスマスBGM'),
    ('Soft acoustic morning BGM', '朝のアコースティックBGM'),
    ('Chill lo-fi BGM', 'チルなLo-Fi BGM'),
    ('Cherry blossom spring BGM', '春の桜BGM'),
    ('Modern corporate BGM', 'モダンな企業BGM'),
    ('Future bass electronic BGM', 'フューチャーベースBGM'),
    ('Uplifting corporate motivational BGM', '前向きな企業モチベBGM'),
    ('Japanese hip hop boom bap BGM', '日本語ヒップホップ・ブームバップBGM'),
    ('Adventurous pirate sea shanty BGM', '冒険的な海賊シーシャンティBGM'),
    ('Asian fantasy BGM', 'アジアン・ファンタジーBGM'),
    ('Anime opening style', 'アニメオープニング風'),
    ('Anime review channel BGM', 'アニメ紹介チャンネルBGM'),
    ('Anime game battle BGM', 'アニメ風バトルゲームBGM'),

    # ── フレーズ (ムード/シーン) ──
    ('soulful and sophisticated', 'ソウルフルで洗練された'),
    ('rebellious energy', '反骨精神あふれるエネルギー'),
    ('short and punchy', '短くパンチのある'),
    ('tense and informative', '緊迫感のある情報的な'),
    ('professional and motivational', 'プロフェッショナルで前向き'),
    ('cute and bright', 'かわいく明るい'),
    ('innocent and cheerful', 'あどけなく陽気'),
    ('light and joyful', '軽やかで楽しい'),
    ('lively and energetic', '生き生きエネルギッシュ'),
    ('festive and magical', '華やかで魔法のような'),
    ('warm and fuzzy', '温かくふんわり'),
    ('bright and uplifting', '明るく高揚感のある'),
    ('soft and gentle', '柔らかく優しい'),
    ('peaceful and optimistic', '穏やかで楽観的'),
    ('gentle and optimistic', '優しく楽観的'),
    ('cozy and warm', '心地よく温かな'),
    ('chill and relaxing', 'チルで心地よい'),
    ('relaxing and peaceful', 'リラックスして穏やか'),
    ('uplifting and modern', '高揚感のあるモダンな'),
    ('moody and emotional', '物憂げで感情的'),
    ('upbeat and energetic', 'アップテンポでエネルギッシュ'),
    ('calm and reflective', '静かで内省的'),
    ('hopeful and warm', '希望に満ち温かな'),
    ('mysterious and dark', 'ミステリアスでダーク'),
    ('eerie and tense', '不気味で緊迫した'),
    ('dramatic and cinematic', 'ドラマチックでシネマティック'),
    ('emotional and heartfelt', '感情的で心のこもった'),
    ('positive energy', 'ポジティブなエネルギー'),
    ('success and achievement feel', '成功と達成感'),
    ('laid-back groove', 'リラックスしたグルーヴ'),
    ('bouncy rhythm', '弾むようなリズム'),
    ('steady beat', '安定したビート'),
    ('mid-tempo', 'ミドルテンポ'),

    # ── 楽器フレーズ ──
    ('jazzy chords', 'ジャジーな和音'),
    ('fast power chords', '疾走するパワーコード'),
    ('soft piano', '柔らかなピアノ'),
    ('sharp piano', '鋭いピアノ'),
    ('clean piano', 'クリーンなピアノ'),
    ('gentle piano', '優しいピアノ'),
    ('warm piano', '温かいピアノ'),
    ('mellow piano', 'メロウなピアノ'),
    ('soft guitar', '柔らかなギター'),
    ('warm guitar', '温かいギター'),
    ('acoustic guitar', 'アコースティックギター'),
    ('electric guitar', 'エレキギター'),
    ('fingerstyle guitar', 'フィンガースタイル・ギター'),
    ('nylon string guitar', 'ナイロン弦ギター'),
    ('classical guitar', 'クラシックギター'),
    ('playful ukulele', '陽気なウクレレ'),
    ('warm strings', '温かいストリングス'),
    ('smooth strings', 'なめらかなストリングス'),
    ('soft strings', '柔らかなストリングス'),
    ('lush strings', '豊かなストリングス'),
    ('soaring strings', '舞い上がるようなストリングス'),
    ('organic drums', 'オーガニックなドラム'),
    ('aggressive drums', '激しいドラム'),
    ('dusty drums', '埃っぽいドラム'),
    ('punchy drums', 'パンチのあるドラム'),
    ('steady percussion', '安定したパーカッション'),
    ('light percussion', '軽やかなパーカッション'),
    ('soft percussion', '柔らかなパーカッション'),
    ('dreamy synth chords', '夢見るようなシンセコード'),
    ('warm synths', '温かいシンセ'),
    ('analog synths', 'アナログシンセ'),
    ('ambient pads', 'アンビエントパッド'),
    ('ethereal pads', '幻想的なパッド'),
    ('emotional drop', '感情的なドロップ'),
    ('airy vocals texture', '透き通ったボーカルの質感'),
    ('chopped soul sample', '刻んだソウルサンプル'),
    ('soul sample', 'ソウルサンプル'),
    ('warm textures', '温かなテクスチャ'),
    ('hazy textures', 'ぼんやりしたテクスチャ'),
    ('dreamy atmosphere', '夢見るような雰囲気'),
    ('warm atmosphere', '温かい雰囲気'),
    ('cinematic atmosphere', 'シネマティックな雰囲気'),
    ('tense atmosphere', '緊迫した雰囲気'),
    ('peaceful atmosphere', '穏やかな雰囲気'),
    ('bedroom producer feel', 'ベッドルームプロデューサー感'),
    ('gentle beat', '穏やかなビート'),
    ('study focus music', '勉強・集中BGM'),
    ('birds singing', '鳥のさえずり'),
    ('fresh breeze', 'さわやかな風'),
    ('peaceful start of day', '穏やかな1日の始まり'),
    ('Japanese spring festival', '日本の春祭り'),
    ('Japanese matsuri', '日本の祭り'),
    ('Japanese festival', '日本の祭り'),
    ('Japanese culture', '日本文化'),
    ('Japanese tradition', '日本の伝統'),
    ('Japanese garden', '日本庭園'),
    ('taiko drums', '太鼓'),
    ('shakuhachi flute', '尺八'),
    ('bamboo flute', '竹笛'),
    ('fireworks night', '花火の夜'),
    ('yukata vibes', '浴衣の風情'),
    ('cozy winter holiday', '心地よい冬休み'),
    ('Japanese Christmas Eve romantic', '日本のクリスマスイブのロマンチック'),
    ('Japanese Christmas Eve', '日本のクリスマスイブ'),
    ('Tokyo cafe night', '東京の夜カフェ'),
    ('Tokyo night', '東京の夜'),
    ('skateboarding montage', 'スケボー映像'),
    ('kids YouTube', 'キッズ向けYouTube'),
    ('professional news theme', 'プロのニューステーマ'),
    ('children educational video', '子ども向け教育動画'),
    ('business presentation', 'ビジネスプレゼン'),
    ('underground rap feel', 'アンダーグラウンドラップ感'),
    ('boom bap', 'ブームバップ'),
    ('coffee shop', 'カフェ'),
    ('late night', '深夜'),
    ('study session', '勉強時間'),
    ('travel vlog', '旅行Vlog'),
    ('food vlog', '料理Vlog'),
    ('cooking vlog', '料理Vlog'),
    ('travel video', '旅行動画'),
    ('food video', '料理動画'),
    ('cooking video', '料理動画'),
    ('relaxing music', 'リラックス音楽'),
    ('background music', 'BGM'),
    ('focus music', '集中BGM'),
    ('relaxation music', 'リラクゼーション音楽'),
    ('chill music', 'チル音楽'),
    ('lounge music', 'ラウンジ音楽'),
    ('chillout music', 'チルアウト音楽'),
    ('YouTube videos', 'YouTube動画'),
    ('YouTube content', 'YouTubeコンテンツ'),
    ('TikTok videos', 'TikTok動画'),
    ('TikTok content', 'TikTokコンテンツ'),
    ('Instagram Reels', 'Instagramリール'),
    ('vlog content', 'Vlogコンテンツ'),
    ('background atmosphere', '背景の雰囲気'),
    ('city pop', 'シティポップ'),
    ('city night', '都会の夜'),
    ('after hours', 'アフターアワー'),
    ('rainy day', '雨の日'),
    ('sunny day', '晴れた日'),
    ('summer day', '夏の日'),
    ('winter night', '冬の夜'),
    ('cherry blossoms', '桜'),
    ('Japanese folk', '日本の民謡'),
    ('Japanese traditional', '日本の伝統'),
    ('traditional Japanese', '日本の伝統'),
    ('anime opening', 'アニメOP'),
    ('anime ending', 'アニメED'),
    ('anime style', 'アニメ風'),
    ('game soundtrack', 'ゲームサウンドトラック'),
    ('game music', 'ゲーム音楽'),
    ('game battle', 'バトルゲーム'),
    ('boss fight', 'ボス戦'),
    ('battle theme', 'バトルテーマ'),
    ('main theme', 'メインテーマ'),
    ('opening theme', 'オープニングテーマ'),
    ('ending theme', 'エンディングテーマ'),
    ('intro music', 'イントロ音楽'),
    ('outro music', 'アウトロ音楽'),
    ('horror movie', 'ホラー映画'),
    ('horror film', 'ホラー映画'),
    ('horror game', 'ホラーゲーム'),
    ('horror story', 'ホラーストーリー'),
    ('documentary style', 'ドキュメンタリー調'),
    ('documentary feel', 'ドキュメンタリー感'),
    ('news theme', 'ニュースのテーマ'),
    ('soundtrack feel', 'サントラ感'),
    ('soundtrack vibe', 'サントラ調'),
    ('movie trailer', '映画予告'),
    ('film trailer', '映画予告'),
    ('epic trailer', 'エピックな予告'),
    ('emotional trailer', '感動的な予告'),
    ('wedding video', '結婚式動画'),
    ('birthday party', 'バースデー'),
    ('happy birthday', 'ハッピーバースデー'),
    ('gym workout', 'ジムワークアウト'),
    ('workout music', 'ワークアウト音楽'),
    ('running music', 'ランニング音楽'),
    ('driving music', 'ドライブ音楽'),
    ('road trip', 'ロードトリップ'),
    ('travel content', '旅コンテンツ'),
    ('aesthetic vibes', 'エステティックな雰囲気'),
    ('aesthetic feel', 'エステティック感'),
    ('retro vibes', 'レトロな雰囲気'),
    ('vintage vibes', 'ヴィンテージな雰囲気'),
    ('nostalgic vibes', 'ノスタルジックな雰囲気'),
    ('Japanese citypop', 'シティポップ'),
    ('city pop vibes', 'シティポップな雰囲気'),
    ('lo-fi hip hop', 'Lo-Fi ヒップホップ'),
    ('lofi hip hop', 'Lo-Fi ヒップホップ'),
    ('lo-fi beats', 'Lo-Fi ビート'),
    ('chillhop beats', 'チルホップビート'),

    # ── 単語 (頻度順) ──
    ('atmosphere', '雰囲気'),
    ('atmospheric', '雰囲気のある'),
    ('content', 'コンテンツ'),
    ('Japanese', '日本'),
    ('japanese', '日本'),
    ('perfect for', '〜にぴったり'),
    ('perfect', 'ぴったり'),
    ('videos', '動画'),
    ('video', '動画'),
    ('music', '音楽'),
    ('vibes', '雰囲気'),
    ('vibe', 'ムード'),
    ('aesthetic', 'エステティック'),
    ('aesthetics', 'エステティック'),
    ('with', 'を伴った'),
    ('and', '＆'),

    # ムード語
    ('warm', '温かな'),
    ('soft', '柔らかな'),
    ('sharp', '鋭い'),
    ('gentle', '優しい'),
    ('soulful', 'ソウルフル'),
    ('sophisticated', '洗練された'),
    ('tense', '緊迫した'),
    ('informative', '情報的な'),
    ('fun', '楽しい'),
    ('playful', '陽気な'),
    ('innocent', 'あどけない'),
    ('cheerful', '明るい'),
    ('bouncy', '弾む'),
    ('cute', 'かわいい'),
    ('bright', '明るい'),
    ('aggressive', '激しい'),
    ('rebellious', '反骨精神あふれる'),
    ('happy', 'ハッピーな'),
    ('whimsical', '気まぐれな'),
    ('silly', 'おどけた'),
    ('colorful', 'カラフルな'),
    ('joyful', '喜びに満ちた'),
    ('lively', '生き生きとした'),
    ('energetic', 'エネルギッシュ'),
    ('cozy', '心地よい'),
    ('festive', '華やかな'),
    ('magical', '魔法のような'),
    ('romantic', 'ロマンチック'),
    ('laid-back', 'リラックスした'),
    ('underground', 'アンダーグラウンド'),
    ('modern', 'モダン'),
    ('positive', '前向きな'),
    ('dreamy', '夢見るような'),
    ('emotional', '感情的な'),
    ('airy', '透き通った'),
    ('uplifting', '高揚感のある'),
    ('fresh', '爽やかな'),
    ('peaceful', '穏やかな'),
    ('optimistic', '楽観的な'),
    ('chill', 'チル'),
    ('hazy', 'ぼんやりした'),
    ('clean', 'クリーンな'),
    ('smooth', 'スムーズな'),
    ('steady', '安定した'),
    ('crisp', 'クリスプな'),
    ('grand', '壮大な'),
    ('epic', 'エピック'),
    ('heroic', '英雄的な'),
    ('mysterious', 'ミステリアス'),
    ('spooky', '不気味な'),
    ('dramatic', 'ドラマチック'),
    ('moody', '物憂げな'),
    ('hopeful', '希望に満ちた'),
    ('heartfelt', '心のこもった'),
    ('nostalgic', 'ノスタルジックな'),
    ('mellow', 'メロウな'),
    ('catchy', 'キャッチーな'),
    ('subtle', '繊細な'),
    ('powerful', 'パワフルな'),
    ('intense', '強烈な'),
    ('elegant', '優雅な'),
    ('graceful', '上品な'),
    ('ethereal', '幻想的な'),
    ('relaxing', 'リラックスした'),
    ('calm', '静かな'),
    ('upbeat', 'アップテンポ'),
    ('eerie', '不気味な'),
    ('dark', 'ダーク'),
    ('funky', 'ファンキー'),
    ('groovy', 'グルーヴィー'),
    ('soaring', '舞い上がる'),
    ('driving', '疾走感のある'),
    ('throbbing', '脈動する'),
    ('sparkling', 'きらめく'),
    ('pulsing', '脈打つ'),
    ('booming', '響き渡る'),
    ('haunting', '心に残る'),
    ('melancholic', '哀愁のある'),
    ('reflective', '内省的な'),
    ('introspective', '内省的な'),
    ('serene', '澄み切った'),
    ('vibrant', '鮮やかな'),
    ('joyous', '喜ばしい'),
    ('exuberant', '溌剌とした'),
    ('majestic', '荘厳な'),
    ('triumphant', '勝ち誇った'),
    ('tender', '繊細な'),
    ('delicate', '繊細な'),
    ('fragile', '儚い'),
    ('poignant', '心に染みる'),
    ('bittersweet', 'ほろ苦い'),

    # 楽器(単体)
    ('piano', 'ピアノ'),
    ('guitar', 'ギター'),
    ('drums', 'ドラム'),
    ('bass', 'ベース'),
    ('synth', 'シンセ'),
    ('synths', 'シンセ'),
    ('strings', 'ストリングス'),
    ('flute', 'フルート'),
    ('violin', 'バイオリン'),
    ('cello', 'チェロ'),
    ('saxophone', 'サックス'),
    ('trumpet', 'トランペット'),
    ('tuba', 'チューバ'),
    ('glockenspiel', 'グロッケン'),
    ('ukulele', 'ウクレレ'),
    ('percussion', 'パーカッション'),
    ('horns', 'ホーン'),
    ('brass', 'ブラス'),
    ('woodwinds', '木管'),
    ('chords', '和音'),
    ('chord', 'コード'),
    ('melody', 'メロディ'),
    ('melodies', 'メロディ'),
    ('harmony', 'ハーモニー'),
    ('beats', 'ビート'),
    ('beat', 'ビート'),
    ('rhythm', 'リズム'),
    ('groove', 'グルーヴ'),
    ('drop', 'ドロップ'),
    ('hook', 'フック'),
    ('vocals', 'ボーカル'),
    ('vocal', 'ボーカル'),
    ('koto', '琴'),
    ('shamisen', '三味線'),
    ('shakuhachi', '尺八'),
    ('taiko', '太鼓'),
    ('erhu', '二胡'),
    ('accordion', 'アコーディオン'),
    ('banjo', 'バンジョー'),
    ('mandolin', 'マンドリン'),
    ('harpsichord', 'チェンバロ'),
    ('harp', 'ハープ'),
    ('marimba', 'マリンバ'),
    ('xylophone', 'シロフォン'),
    ('vibraphone', 'ビブラフォン'),
    ('rhodes', 'ローズ'),
    ('Rhodes', 'ローズ'),
    ('organ', 'オルガン'),
    ('clarinet', 'クラリネット'),
    ('oboe', 'オーボエ'),
    ('bassoon', 'ファゴット'),
    ('tambourine', 'タンバリン'),
    ('snare', 'スネア'),
    ('kick', 'キック'),
    ('hi-hat', 'ハイハット'),
    ('cymbals', 'シンバル'),

    # ジャンル
    ('lo-fi', 'Lo-Fi'),
    ('lofi', 'Lo-Fi'),
    ('chillhop', 'チルホップ'),
    ('future bass', 'フューチャーベース'),
    ('electronic', 'エレクトロニック'),
    ('jazz', 'ジャズ'),
    ('lounge', 'ラウンジ'),
    ('jazz fusion', 'ジャズ・フュージョン'),
    ('rock', 'ロック'),
    ('punk rock', 'パンクロック'),
    ('skate punk', 'スケートパンク'),
    ('cinematic electronic', 'シネマティック・エレクトロニック'),
    ('cinematic', 'シネマティック'),
    ('orchestral', 'オーケストラ'),
    ('cartoon', 'カートゥーン'),
    ('children', '子ども向け'),
    ('childrens', '童謡'),
    ('kids', 'キッズ'),
    ('folk-pop', 'フォークポップ'),
    ('indie-folk', 'インディーフォーク'),
    ('acoustic', 'アコースティック'),
    ('fingerstyle', 'フィンガースタイル'),
    ('corporate', '企業'),
    ('motivational', 'モチベーショナル'),
    ('acoustic pop', 'アコースティックポップ'),
    ('soul', 'ソウル'),
    ('hip hop', 'ヒップホップ'),
    ('hip-hop', 'ヒップホップ'),
    ('rap', 'ラップ'),
    ('Christmas', 'クリスマス'),
    ('waltz', 'ワルツ'),
    ('warm ambient', '温かいアンビエント'),
    ('march-like', '行進曲風'),
    ('instrumental', 'インストゥルメンタル'),
    ('boom bap', 'ブームバップ'),
    ('synthwave', 'シンセウェーブ'),
    ('vaporwave', 'ベイパーウェイブ'),
    ('retro', 'レトロ'),
    ('vintage', 'ヴィンテージ'),
    ('ambient', 'アンビエント'),
    ('reggae', 'レゲエ'),
    ('blues', 'ブルース'),
    ('country', 'カントリー'),
    ('disco', 'ディスコ'),
    ('techno', 'テクノ'),
    ('house', 'ハウス'),
    ('trap', 'トラップ'),
    ('dubstep', 'ダブステップ'),
    ('drum and bass', 'ドラムンベース'),
    ('dnb', 'ドラムンベース'),
    ('classical', 'クラシック'),
    ('baroque', 'バロック'),
    ('jpop', 'J-Pop'),
    ('j-pop', 'J-Pop'),
    ('citypop', 'シティポップ'),
    ('city pop', 'シティポップ'),
    ('anime', 'アニメ'),
    ('game', 'ゲーム'),
    ('vlog', 'Vlog'),
    ('vlogs', 'Vlog'),
    ('podcast', 'ポッドキャスト'),
    ('motivational', 'モチベ'),
    ('aesthetic', 'エステ'),
    ('horror', 'ホラー'),
    ('action', 'アクション'),
    ('adventure', '冒険'),
    ('fantasy', 'ファンタジー'),
    ('sci-fi', 'SF'),
    ('mystery', 'ミステリー'),
    ('comedy', 'コメディ'),
    ('drama', 'ドラマ'),
    ('thriller', 'スリラー'),

    # シーン/季節
    ('cherry blossom', '桜'),
    ('Sakura', '桜'),
    ('sakura', '桜'),
    ('spring', '春'),
    ('summer', '夏'),
    ('autumn', '秋'),
    ('fall', '秋'),
    ('winter', '冬'),
    ('morning', '朝'),
    ('night', '夜'),
    ('evening', '夕暮れ'),
    ('afternoon', '午後'),
    ('rain', '雨'),
    ('rainy', '雨の'),
    ('snow', '雪'),
    ('snowy', '雪の'),
    ('snowfall', '雪'),
    ('wind', '風'),
    ('windy', '風の'),
    ('breeze', 'そよ風'),
    ('cafe', 'カフェ'),
    ('window', '窓'),
    ('forest', '森'),
    ('beach', 'ビーチ'),
    ('ocean', '海'),
    ('mountain', '山'),
    ('city', '街'),
    ('town', '町'),
    ('garden', '庭'),
    ('park', '公園'),
    ('home', '家'),
    ('house', '家'),
    ('school', '学校'),
    ('library', '図書館'),
    ('restaurant', 'レストラン'),
    ('bar', 'バー'),
    ('pub', 'パブ'),
    ('train', '電車'),
    ('plane', '飛行機'),
    ('YouTube', 'YouTube'),
    ('TikTok', 'TikTok'),
    ('Instagram', 'Instagram'),
    ('Vlog', 'Vlog'),
    ('study', '勉強'),
    ('focus', '集中'),
    ('travel', '旅行'),
    ('cooking', '料理'),
    ('food', '料理'),
    ('coffee', 'コーヒー'),
    ('shop', 'カフェ'),
    ('Tokyo', '東京'),
    ('Kyoto', '京都'),
    ('Shibuya', '渋谷'),
    ('Osaka', '大阪'),
    ('Japan', '日本'),
    ('Asian', 'アジア'),
    ('asian', 'アジアン'),
    ('western', '西洋'),
    ('eastern', '東洋'),
    ('tropical', 'トロピカル'),
    ('urban', '都会の'),
    ('rural', '田園の'),
    ('night', '夜'),
    ('day', '日'),
    ('summer', '夏'),
    ('winter', '冬'),
    ('Christmas Eve', 'クリスマスイブ'),

    # 連結語/修飾
    ('feel', '感'),
    ('vibe', '感'),
    ('mood', 'ムード'),
    ('style', 'スタイル'),
    ('flavor', '風味'),
    ('texture', 'テクスチャ'),
    ('background', '背景'),

    # 動詞
    ('singing', '歌う'),
    ('playing', '奏でる'),
    ('whispering', 'ささやく'),

    # 機能語/接続
    ('for', '〜向け'),
    ('the', ''),
    ('a ', ''),
    ('an ', ''),
    ('is ', ''),
    ('are ', ''),
    ('to ', ''),

    # 残りの定型
    ('BGM', 'BGM'),
    ('ASMR', 'ASMR'),
    ('Lo-fi', 'Lo-Fi'),
    ('Lo-Fi', 'Lo-Fi'),
]

# 大文字小文字を区別せずソート (長い順)
PHRASE_PAIRS_SORTED = sorted(PHRASE_PAIRS, key=lambda p: -len(p[0]))


def is_japanese(s: str) -> bool:
    return any('\u3040' <= c <= '\u30ff' or '\u4e00' <= c <= '\u9fff' for c in s)


def translate_title(t: str) -> str:
    if is_japanese(t):
        return t
    if t in TITLE_FULL:
        return TITLE_FULL[t]
    parts = []
    # 単語ごとに置換 (case-insensitive)
    lc = {k.lower(): v for k, v in TITLE_WORDS.items()}
    for w in re.split(r'(\s+)', t):
        if w.strip() == '': continue
        bare = re.sub(r"[^\w'-]", '', w)
        if bare.lower() in lc:
            parts.append(lc[bare.lower()])
        else:
            parts.append(w)
    # 中点で連結
    out = '・'.join(p for p in parts if p)
    return out


def translate_desc(d: str) -> str:
    if not d: return ''
    if is_japanese(d):
        return d
    s = d
    # フレーズ単位置換 (長いものから)
    for en, ja in PHRASE_PAIRS_SORTED:
        # 英字フレーズ → 単語境界で囲む
        if en[0].isalpha() and en[-1].isalpha() and not en[-1] == 'h':
            pat = re.compile(r'\b' + re.escape(en) + r'\b', re.IGNORECASE)
        else:
            pat = re.compile(re.escape(en), re.IGNORECASE)
        s = pat.sub(ja, s)
    # 残った "with" などを掃除
    s = re.sub(r'\bwith\b', '', s, flags=re.IGNORECASE)
    s = re.sub(r'\bof\b', 'の', s, flags=re.IGNORECASE)
    s = re.sub(r'\bin\b', 'の', s, flags=re.IGNORECASE)
    # カンマ → 読点
    s = re.sub(r'\s*,\s*', '、', s)
    # 連続する空白・記号整理
    s = re.sub(r'\s+', '', s)
    s = re.sub(r'、+', '、', s)
    s = re.sub(r'^、|、$', '', s)
    if s and not s.endswith(('。', '！', '？')):
        s = s + '。'
    return s


def main():
    songs = json.loads(SRC.read_text(encoding='utf-8'))
    if not BAK.exists():
        shutil.copy(SRC, BAK)
        print(f'✔ backup: {BAK.relative_to(ROOT)}')

    n_t = n_d = 0
    untranslated = set()
    for s in songs:
        t0, d0 = s.get('title', ''), s.get('description', '')
        t1, d1 = translate_title(t0), translate_desc(d0)
        if t1 != t0:
            s['title'] = t1; n_t += 1
        if d1 != d0:
            s['description'] = d1; n_d += 1
        for w in re.findall(r'[A-Za-z]{3,}', d1):
            if w.lower() not in {'bgm','lo-fi','lofi','j-pop','tokyo','kyoto','tiktok','youtube','instagram','vlog','asmr','rhodes','dnb','sakura','matsuri','yukata'}:
                untranslated.add(w)

    SRC.write_text(json.dumps(songs, ensure_ascii=False, indent=0), encoding='utf-8')
    print(f'✔ saved: {SRC.relative_to(ROOT)} ({len(songs)} songs)')
    print(f'  - titles changed:       {n_t}')
    print(f'  - descriptions changed: {n_d}')
    print()
    if untranslated:
        print(f'未訳語 (description内, 出現上位):')
        from collections import Counter
        cnt = Counter()
        for s in songs:
            for w in re.findall(r'[A-Za-z]{3,}', s.get('description','')):
                if w.lower() not in {'bgm','lo-fi','lofi','j-pop','tokyo','kyoto','tiktok','youtube','instagram','vlog','asmr','rhodes','dnb','sakura','matsuri','yukata'}:
                    cnt[w.lower()] += 1
        for w, c in cnt.most_common(30):
            print(f'  {c:>4}  {w}')


if __name__ == '__main__':
    main()
